### ISSUE TITLE
启动后就报错

### ISSUE THREAD

**Issue by easycnn** [swoft-cloud/swoft-cli#10]
Work Information
  current pid 95624
  current dir /Applications/MAMP/htdocs/swoft
  php binFile php
  target path /Applications/MAMP/htdocs/swoft
  watch dirs  app, config
  entry file  /Applications/MAMP/htdocs/swoft/bin/swoft
  execute cmd php /Applications/MAMP/htdocs/swoft/bin/swoft http:start

Watched Directories
  /Applications/MAMP/htdocs/swoft/app
  /Applications/MAMP/htdocs/swoft/config

[SWOFTCLI] Start swoft server
[SWOFTCLI] Server(pid 95627) exited (signal 0, code 255)
[SWOFTCLI] Server non-zero status exit
restart?(y/n) >

**Comment by inhere** [comment]
发了新版本了
