### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by dan381006472** [swoft-cloud/swoft-cli#11]
root@8a5b832d5f01:~# wget https://github.com/swoft-cloud/swoft-cli/releases/download/VERSION/swoftcli.phar
--2019-08-29 11:13:25--  https://github.com/swoft-cloud/swoft-cli/releases/download/VERSION/swoftcli.phar
Resolving github.com (github.com)... 13.229.188.59
Connecting to github.com (github.com)|13.229.188.59|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-08-29 11:13:26 ERROR 404: Not Found.

**Comment by dan381006472** [comment]
下载地址 失效

**Comment by inhere** [comment]
:( ... 不是提示了吗. 文档里和这里的readme都写了提示的。

> Notice: please replace the `VERSION` to specified version

**Comment by dan381006472** [comment]
对不起 没看仔细。文档里 这个路径好像写错了。好像应该是 /usr
mv swoftcli.phar /user/local/bin/swoftcli

**Comment by inhere** [comment]
ok 谢谢提醒。 我改下 `user -> usr`

**Comment by dan381006472** [comment]
谢谢你这么及时的回复，我以后一定先看仔细文档再提问题 😂

**Comment by dan381006472** [comment]
ok
