### ISSUE TITLE
v0.1.3 启用报错

### ISSUE THREAD

**Issue by hupeng312** [swoft-cloud/swoft-cli#15]
root@be24a4009222:/var/www# php swoftcli.phar

Fatal error: Uncaught PharException: phar "/var/www/swoftcli.phar" has a broken signature in /var/www/swoftcli.phar:9
Stack trace:
#0 /var/www/swoftcli.phar(9): Phar::mapPhar('swoftcli.phar')
#1 {main}
  thrown in /var/www/swoftcli.phar on line 9

其他系统信息:
root@be24a4009222:/var/www# which php
/usr/local/bin/php

root@be24a4009222:/var/www# php -v
PHP 7.2.23 (cli) (built: Oct 17 2019 15:52:12) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies

root@be24a4009222:/var/www# php -i | grep phar
Registered PHP Streams => https, ftps, compress.zlib, php, file, glob, data, http, ftp, phar, zip
Phar-based phar archives => enabled
Tar-based phar archives => enabled
ZIP-based phar archives => enabled
phar.cache_list => no value => no value
phar.readonly => On => On
phar.require_hash => On => On
root@be24a4009222:/var/www#

**Comment by inhere** [comment]
我这没有复现。。。
