### ISSUE TITLE
php升级到7.4.0报错

### ISSUE THREAD

**Issue by EthanChenLi** [swoft-cloud/swoft-cli#16]
PHP: 7.4.0, Swoft: 2.0.7, Swoole: 4.4.13RC2

PHP Fatal error:  Uncaught ErrorException: Array and string offset access syntax with curly braces is deprecated in phar:///usr/local/bin/swoftcli/vendor/toolkit/cli-utils/src/Flags.php:313
Stack trace:
#0 phar:///usr/local/bin/swoftcli/vendor/swoft/error/src/DefaultErrorDispatcher.php(64): Swoft\Error\DefaultErrorDispatcher->handleError(8192, 'Array and strin...', 'phar:///usr/loc...', 313)
#1 [internal function]: Swoft\Error\DefaultErrorDispatcher->Swoft\Error\{closure}()
#2 {main}
  thrown in phar:///usr/local/bin/swoftcli/vendor/toolkit/cli-utils/src/Flags.php on line 313

Fatal error: Uncaught ErrorException: Array and string offset access syntax with curly braces is deprecated in phar:///usr/local/bin/swoftcli/vendor/toolkit/cli-utils/src/Flags.php:313
Stack trace:
#0 phar:///usr/local/bin/swoftcli/vendor/swoft/error/src/DefaultErrorDispatcher.php(64): Swoft\Error\DefaultErrorDispatcher->handleError(8192, 'Array and strin...', 'phar:///usr/loc...', 313)
#1 [internal function]: Swoft\Error\DefaultErrorDispatcher->Swoft\Error\{closure}()
#2 {main}
  thrown in phar:///usr/local/bin/swoftcli/vendor/toolkit/cli-utils/src/Flags.php on line 313

**Comment by inhere** [comment]
已修复 https://github.com/php-toolkit/cli-utils/commit/0740abf2589c25c6c6daa67837b3b251cfbc5889
下个版本发布
