### ISSUE TITLE
无法单独创建tcp应用

### ISSUE THREAD

**Issue by tanlanxing** [swoft-cloud/swoft-cli#18]
在创建单独的tcp应用时报错：
php swoftcli.phar create:app --debug 4 --refresh --type tcp node
- Validate project information
Project Information
  name        node
  type        tcp
  repoUrl     https://github.com/swoft-cloud/swoft-tcp-project.git
  workDir     /xxx/devel/php
  projectPath /xxx/devel/php/node

Ensure create application ?
Please confirm(yes|no)[default:yes]: yes
- Begin create the new project: node
- Clone Repo https://github.com/swoft-cloud/swoft-tcp-project.git
> cd /var/folders/c4/hg4h6syj5x1d5qq33bldkr1c0000gn/T/swoft-app-demos && git clone --depth 1 https://github.com/swoft-cloud/swoft-tcp-project.git
Cloning into 'swoft-tcp-project'...
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (3/3), done.
- Copy project files from local cache
- Remove .git directory on new project
> cp -R /var/folders/c4/hg4h6syj5x1d5qq33bldkr1c0000gn/T/swoft-app-demos/swoft-tcp-project /xxx/devel/php/node && rm -rf /xxx/devel/php/node/.git
- Project: /xxx/devel/php/node created
- Begin run composer install for init project
> cd /xxx/devel/php/node && composer install
Composer could not find a composer.json file in /xxx/devel/php/node
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
[ERROR] exec command fail

https://github.com/swoft-cloud/swoft-tcp-project.git 是空的

**Comment by inhere** [comment]
@tanlanxing 
:( 因为很少人用这个 https://github.com/swoft-cloud/swoft-tcp-project.git 就没有弄。

有兴趣可以帮忙弄一个 :)
