### ISSUE TITLE
Can I change my php into binary version swoole's php?

### ISSUE THREAD

**Issue by lzylyd** [swoft-cloud/swoft-cli#19]
I use the[ binary version of swoole ](https://www.swoole.com/page/download)  can I change the cli tool's running enviromenet into the binary version?

**Comment by lzylyd** [comment]
用的二进制版本的 swoole ,可以改swoft-cli运行的php为swoole二进制php-cli么?

**Comment by inhere** [comment]
不是太明白。。。

> 可以用指定版本的PHP运行 swoft-cli: `php72 swoft-cli.phar`
