### ISSUE TITLE
有问题还会一直重试

### ISSUE THREAD

**Issue by ohmygd** [swoft-cloud/swoft-cli#6]
重试应该是代码 保存的动作的时候 才会重试

**Comment by inhere** [comment]
重试啥？

**Comment by ohmygd** [comment]
> 重试啥？

重新运行代码呀,  有错误还是一直重新运行代码, 页面就一直弹出报错信息

**Comment by inhere** [comment]
截个图我看下

**Comment by ohmygd** [comment]
> 截个图我看下

![image](https://user-images.githubusercontent.com/19659483/61356703-7e18ba80-a8a9-11e9-9837-1ebe3f9a9535.png)

**Comment by inhere** [comment]
我是检查非0状态退出的就不会重试，0的话还会继续重试。后面再优化吧

**Comment by inhere** [comment]
发了新版本，稍微优化了下
