### ISSUE TITLE
Mac httpserver重启失败

### ISSUE THREAD

**Issue by Sentiger** [swoft-cloud/swoft-cli#7]
2019/07/23-14:57:46 [INFO] Swoft\Redis\Listener\WorkerStopAndErrorListener:handle(52) Close 0 redis connection on workerStop!
2019/07/23-14:57:46 [INFO] Swoft\Db\Listener\WorkerStopAndErrorListener:handle(50) Close 0 database connection on workerStop!
2019/07/23-14:57:46 [INFO] Swoft\Db\Listener\WorkerStopAndErrorListener:handle(50) Close 0 database connection on workerStop!
2019/07/23-14:57:46 [INFO] Swoft\Db\Listener\WorkerStopAndErrorListener:handle(50) Close 0 database connection on workerStop!
2019/07/23-14:57:46 [INFO] Swoft\Db\Listener\WorkerStopAndErrorListener:handle(50) Close 0 database connection on workerStop!
2019/07/23-14:57:46 [INFO] Swoft\Db\Listener\WorkerStopAndErrorListener:handle(50) Close 0 database connection on workerStop!
2019/07/23-14:57:46 [INFO] Swoft\Db\Listener\WorkerStopAndErrorListener:handle(50) Close 0 database connection on workerStop!
[2019-07-23 14:57:47 #84709.2]	INFO	Server is shutdown now
[2019-07-23 14:57:48 #84709.2]	INFO	Server is shutdown now
[2019-07-23 14:57:49 #84709.2]	INFO	Server is shutdown now
[ERROR] Stop sever is failed

**Comment by inhere** [comment]
mac 现在有点问题，stop 时间太长了。 我这要 20-30秒，超时了。

**Comment by Sentiger** [comment]
Mac中使用docker也是重启很慢，到达这步
019/07/23-17:28:15 [INFO] Swoft\Processor\EnvProcessor:handle(52) Env file(/Users/sentiger/code/swoft/.env) is loaded
2019/07/23-17:28:15 [DEBUG] Swoft\Processor\AnnotationProcessor:notifyHandler(63) No autoloader on {PROJECT}/vendor/composer/../phpdocumentor/reflection-common/src
2019/07/23-17:28:15 [DEBUG] Swoft\Processor\AnnotationProcessor:notifyHandler(63) No autoloader on {PROJECT}/vendor/composer/../phpdocumentor/reflection-docblock/src
2019/07/23-17:28:15 [DEBUG] Swoft\Processor\AnnotationProcessor:notifyHandler(63) No autoloader on {PROJECT}/vendor/composer/../phpdocumentor/type-resolver/src
2019/07/23-17:28:15 [DEBUG] Swoft\Processor\AnnotationProcessor:notifyHandler(63) No autoloader on {PROJECT}/vendor/com

**Comment by inhere** [comment]
mac 使用docker挂载本地文件？这不是更慢

**Comment by Sentiger** [comment]
不挂在也是很慢，而且如果不挂在怎么开发代码同步

**Comment by Sentiger** [comment]
希望修复下Mac下的swoftcli，目前针对代码热加载只对http:searver有我问题

**Comment by inhere** [comment]
更新swoftcli 和 swoole 版本
