### ISSUE TITLE
gen生成代码问题

### ISSUE THREAD

**Issue by WangNingkai** [swoft-cloud/swoft-cli#9]
![image](https://user-images.githubusercontent.com/23030927/63174107-e35ff700-c073-11e9-94de-d298975c9c4b.png)

不知道开发注意到了吗，这里生成代码有个命名空间的拼写错误，会导致生成的命令无法使用。

**Comment by inhere** [comment]
en 是有几个类生成的有点错误，你可以生成后手动改下。也可以在生成时手动设置下命名空间。

应该会在下个版本再修复。
